
[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dimensions = {columns = 120, lines = 35 }

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(https://|http://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[font]
size = 11.0

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[cursor]
style = {shape = "Beam"}

[selection]
save_to_clipboard = true

[general]
# Full Config Details: https://alacritty.org/config-alacritty.html


import = ["/home/marcel/.config/alacritty/themes/nord.toml"]
