# Full Config Details: https://alacritty.org/config-alacritty.html


import = ["/home/marcel/.config/alacritty/themes/nord.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dimensions = {columns = 120, lines = 35 }

[font]
size = 11.0

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[cursor]
style = {shape = "Beam"}

[selection]
save_to_clipboard = true
