" General
set noswapfile
set noundofile
set nobackup
set nocompatible
syntax on
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set tw=79
set path+=**
set wildmenu
filetype plugin on

" Plugins
call plug#begin()

Plug 'vimwiki/vimwiki'
Plug 'plasticboy/vim-markdown'
Plug 'junegunn/vim-easy-align'
Plug 'preservim/nerdtree'
Plug 'arcticicestudio/nord-vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'michal-h21/vim-zettel'

call plug#end()

" Appearance
set background=dark
set termguicolors
colorscheme nord
set number
set showcmd
filetype indent on
set showmatch

" searching
set incsearch
set hlsearch

" keybindings
nnoremap t <C-]>
nnoremap <SPACE> <S-/>
nnoremap ö :
inoremap jk <ESC>
map <C-n> :NERDTreeToggle<CR>
noremap <F12> :vertical belowright terminal<CR>

" NERDTree
let g:NERDTreeDirArrowExpandable = '>'
let g:NERDTreeDirArrowCollapsible = 'v'

" netrw
let g:netrw_banner = 0
let g:netrw_winsize = 25
let g:netrw_browse_split = 4

" align GitHub-flavored Markdown tables
au FileType markdown vmap <Leader><Bslash> :EasyAlign*<Bar><Enter>

" grep trough notes
command! -nargs=1 Ngrep vimgrep "<args>" $NOTES_DIR/**/*.md
nnoremap <leader>nn :Ngrep

" open quickfix list in vertical pane
command! Vlist botright vertical copen | vertical resize 50
nnoremap <leader>v :Vlist<CR>

" using fzf to find notes
nnoremap 'n :Files $NOTES_DIR<CR>

" Settings for Vimwiki and vim-zettel
let g:vimwiki_list = [{'path':'~/zk', 'ext':'.md', 'syntax':'markdown', 'links_space_char':'-'}]
let g:zettel_format = "%y%m%d-%H%M-%title"

" include .md extension in wiki-links
let g:vimwiki_markdown_link_ext = 1 

" searching
let g:nv_search_paths = ['~/zk']

" zettelkasten key mapping
nnoremap <leader>zn :ZettelNew<space>
