# ls
alias ls='exa --group-directories-first'
alias ll='ls -lF'
alias la='ls -laF'

# color output for grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# preserve user environment with sudo
alias sudo='sudo -E'

# calcurse
alias calcurse='calcurse -D $HOME/sync/data/calcurse'

# todo.txt
alias t='todo.sh -d ~/.config/todo/config'

# taskbook
alias tb='taskbook'
